name: Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        sbt: ['1.3.9', '1.3.10', '1.3.11', '1.3.12', '1.3.13']

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chmodas/docker-scala-sbt:11
    - name: Publish the Docker image
      if: github.event_name != 'pull_request'
      run: |
        echo ${{ secrets.DOCKER_HUB }} | docker login --username ${{ secrets.DOCKER_UID }} --password-stdin
        docker push chmodas/docker-scala-sbt:11
        docker logout
