name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chmodas/docker-scala-sbt:latest
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB }} | docker login --username ${{ secrets.DOCKER_UID }} --password-stdin
    - name: Publish the Docker image
      run: docker push chmodas/docker-scala-sbt:latest
    - name: Logout from Docker Hub
      run: docker logout
